#!/usr/bin/env python3
"""Release bump: gather PRs merged since the last tag, write a new dated
CHANGELOG entry, propagate to packageManifest.json releaseNotes + README
Version History, bump all 4 version strings, update dateReleased.

Invoked by .github/workflows/release.yml after a PR with a release:* label
merges to main. Contributors never touch bookkeeping files — the bot gathers
release notes from merged PR titles (and optional '## Release notes' sections
in PR bodies) since the previous vX.Y.Z tag.

Reads env:
  LABEL               - release:patch | release:minor | release:major
  TRIGGER_PR_NUMBER   - number of the PR that triggered this workflow (fallback)

Outputs (GITHUB_OUTPUT):
  new_version=X.Y.Z

Files modified:
  CHANGELOG.md, packageManifest.json, README.md,
  hubitat-mcp-server.groovy, hubitat-mcp-rule.groovy
"""

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "packageManifest.json"
CHANGELOG = ROOT / "CHANGELOG.md"
README = ROOT / "README.md"
SERVER = ROOT / "hubitat-mcp-server.groovy"
RULE = ROOT / "hubitat-mcp-rule.groovy"

SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+$")


def run(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(args, capture_output=True, text=True, check=check, cwd=ROOT)


def latest_tag() -> str | None:
    """Return the latest 'v*.*.*' tag, or None if no tags exist."""
    try:
        result = run("git", "describe", "--tags", "--abbrev=0", "--match", "v*.*.*")
        tag = result.stdout.strip()
        if SEMVER_RE.match(tag.lstrip("v")):
            return tag
    except subprocess.CalledProcessError:
        pass
    return None


def current_manifest_version() -> str:
    version = json.loads(MANIFEST.read_text())["version"]
    if not SEMVER_RE.match(version):
        raise ValueError(f"Manifest version not strict semver: {version!r}")
    return version


def compute_next(current: str, label: str) -> str:
    major, minor, patch = (int(x) for x in current.split("."))
    if label == "release:major":
        return f"{major + 1}.0.0"
    if label == "release:minor":
        return f"{major}.{minor + 1}.0"
    if label == "release:patch":
        return f"{major}.{minor}.{patch + 1}"
    raise ValueError(f"Unknown release label: {label!r}")


def merged_pr_numbers_since(tag: str | None) -> list[int]:
    """Return PR numbers referenced in commit subjects between `tag` (exclusive)
    and HEAD, in chronological order (oldest first). Handles both merge-commit
    format ('Merge pull request #NN') and squash-merge format ('Title (#NN)').
    Deduplicates in case multiple commits reference the same PR.
    """
    if tag is None:
        return []
    try:
        result = run("git", "log", f"{tag}..HEAD", "--format=%s")
    except subprocess.CalledProcessError:
        return []
    numbers: list[int] = []
    seen: set[int] = set()
    pr_re = re.compile(r"(?:Merge pull request #| \(#)(\d+)\b")
    for line in result.stdout.splitlines():
        m = pr_re.search(line)
        if m:
            n = int(m.group(1))
            if n not in seen:
                seen.add(n)
                numbers.append(n)
    return list(reversed(numbers))


def fetch_pr(number: int) -> dict | None:
    """Fetch PR metadata + its branch commits via gh CLI. Returns None on failure."""
    try:
        result = run(
            "gh", "pr", "view", str(number),
            "--json", "number,title,url,author,commits",
        )
    except subprocess.CalledProcessError:
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


def main_commit_description(commits: list[dict]) -> str:
    """Return the extended description (body) from the PR's main commit.

    A git commit message is 'subject\\n\\nbody'. The body is the extended
    description — where the author explains the WHY. We use the FIRST commit
    on the branch (the main commit that does the real work); follow-up
    commits like doc fixups or typo corrections typically have no body and
    aren't release-notes material.

    If the first commit has no body, return empty — don't walk the list
    looking for one, because that would surface a fixup's body instead of
    the main commit's actual (empty) description, which would be misleading.

    Note: we read per-branch-commit bodies (from 'gh pr view --json commits'),
    NOT the merge commit body. Merge-commit-strategy merge commits typically
    have a body that's just the PR title, which is useless noise.
    """
    if not commits:
        return ""
    body = (commits[0].get("messageBody") or "").strip()
    if not body:
        return ""
    # Strip trailers / autogenerated lines. Anchor each pattern to its own
    # line and consume at most one preceding newline so we don't accidentally
    # eat paragraph separators if the trailer appears mid-message.
    body = re.sub(r"(?:\n|^)Co-[Aa]uthored-[Bb]y:[^\n]*", "", body)
    body = re.sub(r"(?:\n|^)🤖 Generated with[^\n]*", "", body)
    body = re.sub(r"\n{3,}", "\n\n", body).strip()
    return body


def indent_continuation(text: str) -> str:
    """Indent every line by 2 spaces so the text is a valid list-item
    continuation under a markdown bullet. Preserves paragraph breaks."""
    return "\n".join(
        f"  {line}" if line else "" for line in text.splitlines()
    )


def build_bullets(pr_numbers: list[int]) -> list[str]:
    """Return one markdown bullet per PR. Each bullet has:
      - Line 1: PR title + '([#NN](url), @author)' suffix
      - Optional continuation: the extended commit description (body) from
        the PR's main commit, indented 2 spaces so it renders as a
        sub-paragraph in CommonMark. Commit subjects are NOT duplicated —
        the PR title already serves that role.
    """
    bullets = []
    for n in pr_numbers:
        pr = fetch_pr(n)
        if pr is None:
            bullets.append(f"- PR #{n}")
            continue
        author = (pr.get("author") or {}).get("login", "")
        url = pr["url"]
        title = " ".join(pr["title"].splitlines()).strip()
        suffix = f"([#{n}]({url}), @{author})" if author else f"([#{n}]({url}))"
        header = f"- {title} {suffix}"

        description = main_commit_description(pr.get("commits") or [])
        if description:
            bullets.append(f"{header}\n\n{indent_continuation(description)}")
        else:
            bullets.append(header)
    return bullets


def bump_groovy_header(path: Path, new_version: str) -> None:
    text = path.read_text()
    new_text, n = re.subn(
        r"^(\s*\*\s*Version:\s*)\d+\.\d+\.\d+(.*)$",
        rf"\g<1>{new_version}\g<2>",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if n != 1:
        raise RuntimeError(f"Could not find version header in {path.name}")
    path.write_text(new_text)


def bump_current_version_fn(path: Path, new_version: str) -> None:
    text = path.read_text()
    new_text, n = re.subn(
        r'(def\s+currentVersion\s*\(\)\s*\{\s*\n\s*return\s+")\d+\.\d+\.\d+(")',
        rf"\g<1>{new_version}\g<2>",
        text,
        count=1,
    )
    if n != 1:
        raise RuntimeError(f"Could not find currentVersion() in {path.name}")
    path.write_text(new_text)


def bump_manifest(new_version: str, paragraph: str) -> None:
    manifest = json.loads(MANIFEST.read_text())
    manifest["version"] = new_version
    manifest["dateReleased"] = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    manifest["releaseNotes"] = paragraph + "\n\n" + manifest["releaseNotes"]
    MANIFEST.write_text(json.dumps(manifest, indent=4, ensure_ascii=False) + "\n")
    json.loads(MANIFEST.read_text())  # round-trip validation


def prepend_changelog_entry(new_version: str, date: str, bullets: list[str]) -> None:
    text = CHANGELOG.read_text()
    # Keep the list tight (no blank lines between bullets, so renders without
    # per-item <p> wrappers) when every bullet is single-line. If any bullet
    # has an indented continuation, the list is already loose by virtue of
    # the internal blank lines inside that bullet, so use \n\n separators to
    # keep the output visually readable in the raw source.
    any_multiline = any("\n" in b for b in bullets)
    separator = "\n\n" if any_multiline else "\n"
    entry = f"## [{new_version}] - {date}\n\n" + separator.join(bullets) + "\n\n"
    m = re.search(r"^## \[", text, re.MULTILINE)
    if m is None:
        raise RuntimeError("CHANGELOG.md has no existing '## [X.Y.Z]' heading to insert before")
    new_text = text[: m.start()] + entry + text[m.start():]
    CHANGELOG.write_text(new_text)


def bullet_title_line(bullet: str) -> str:
    """Return just the first line of a bullet (the title/link line), stripping
    any indented continuation that follows it."""
    first = bullet.splitlines()[0] if bullet else ""
    return first.strip()


def prepend_readme_bullet(new_version: str, bullets: list[str]) -> None:
    """Prepend a single compact bullet summarizing all PRs in this release.

    The README Version History entry keeps only the titles + PR refs — the
    extended descriptions live in CHANGELOG.md and packageManifest.json so
    README stays scannable.
    """
    text = README.read_text()
    summaries = []
    refs = []
    for b in bullets:
        title_line = bullet_title_line(b)
        body = title_line[2:].strip() if title_line.startswith("- ") else title_line
        link_match = re.search(r"\[#(\d+)\]\(([^)]+)\)", body)
        if link_match:
            refs.append(link_match.group(0))
            # Author suffix is optional (author may be empty).
            body = re.sub(
                r"\s*\(\[#\d+\]\([^)]+\)(?:,?\s*@[\w-]*)?\)\s*$",
                "",
                body,
            ).strip()
        summaries.append(_strip_trailing_period(body))
    summary = "; ".join(summaries)
    bullet = (
        f"- **v{new_version}** - {summary}. PRs: {', '.join(refs)}\n"
        if refs
        else f"- **v{new_version}** - {summary}\n"
    )
    new_text, n = re.subn(
        r"(## Version History\s*\n+)",
        rf"\g<1>{bullet}",
        text,
        count=1,
    )
    if n != 1:
        raise RuntimeError("README.md missing '## Version History' section")
    README.write_text(new_text)


def paragraph_from_bullets(bullets: list[str]) -> str:
    """Flatten bullets into one prose paragraph for packageManifest.json releaseNotes.

    HPM shows this string to end users when they consider updating, so the
    goal is the commit message content (title + main commit description), not
    developer-facing metadata. We strip the PR reference (number, URL,
    author) from the title line — it's not useful to an HPM user in the
    update-prompt UI. CHANGELOG.md keeps the full PR reference for
    developers browsing the repo; the manifest stays terse.

    Each bullet can be single-line (title only) or multi-line (title plus an
    indented continuation from the main commit's extended description).
    Paragraph breaks inside a bullet body are preserved as sentence breaks
    (`. `) so the flattened prose reads as a series of sentences rather than
    a run-on.
    """
    parts = []
    for b in bullets:
        if not b:
            continue
        lines = b.splitlines()
        title_line = lines[0]
        if title_line.startswith("- "):
            title_line = title_line[2:]
        title_line = title_line.strip()
        # Strip the PR reference suffix '([#NN](url), @author)' (or without
        # the author). Author suffix is optional; the regex makes that group
        # optional too.
        title_line = re.sub(
            r"\s*\(\[#\d+\]\([^)]+\)(?:,?\s*@[\w-]*)?\)\s*$",
            "",
            title_line,
        ).strip()

        # Group continuation lines into paragraphs (separated by blank lines).
        paragraphs: list[list[str]] = []
        current: list[str] = []
        for ln in lines[1:]:
            s = ln.strip()
            if s:
                current.append(s)
            elif current:
                paragraphs.append(current)
                current = []
        if current:
            paragraphs.append(current)
        body_flat = ". ".join(
            _strip_trailing_period(" ".join(para)) for para in paragraphs
        )

        combined = f"{title_line}: {body_flat}" if body_flat else title_line
        # Convert any remaining '[#NN](url)' markdown links that appeared
        # inside the commit body (e.g. a cross-reference to another PR) into
        # '#NN (url)' plain text. HPM renders releaseNotes as plain text,
        # so raw markdown links would show up ugly.
        combined = re.sub(r"\[#(\d+)\]\(([^)]+)\)", r"#\1 (\2)", combined)
        parts.append(_strip_trailing_period(combined.strip()))
    return " / ".join(parts) + "."


def _strip_trailing_period(text: str) -> str:
    """Remove exactly ONE trailing period, preserving ellipses or version-like
    suffixes (e.g., 'v1.0.' keeps the penultimate '.0', an ellipsis '...'
    stays intact)."""
    return re.sub(r"(?<=[^.])\.$", "", text)


def write_github_output(key: str, value: str) -> None:
    path = os.environ.get("GITHUB_OUTPUT")
    if path:
        with open(path, "a") as f:
            f.write(f"{key}={value}\n")


def main() -> int:
    label = os.environ.get("LABEL", "").strip()
    trigger_pr = os.environ.get("TRIGGER_PR_NUMBER", "").strip()
    if not label:
        print("::error::LABEL env var not set", file=sys.stderr)
        return 1

    tag = latest_tag()
    current = tag.lstrip("v") if tag else current_manifest_version()
    new_version = compute_next(current, label)
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    pr_numbers = merged_pr_numbers_since(tag)
    if not pr_numbers and trigger_pr:
        pr_numbers = [int(trigger_pr)]
    if not pr_numbers:
        print("::warning::No PRs found to include in release; using placeholder entry")
        bullets = [f"- Release {new_version}"]
    else:
        bullets = build_bullets(pr_numbers)

    paragraph = f"v{new_version} - " + paragraph_from_bullets(bullets)

    prepend_changelog_entry(new_version, date, bullets)
    bump_groovy_header(SERVER, new_version)
    bump_current_version_fn(SERVER, new_version)
    bump_groovy_header(RULE, new_version)
    bump_manifest(new_version, paragraph)
    prepend_readme_bullet(new_version, bullets)

    write_github_output("new_version", new_version)
    print(f"::notice::Bumped {current} -> {new_version} ({len(bullets)} PR(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
