'use strict';function jq(a){return"#"+a.replace(/(:|\.|\[|\]|,|\(|\))/g,"\\$1")}var nextElement,refreshInterval,debug=!1;class TaskQueue{constructor(){this.queue=Promise.resolve()}add(a){return this.queue=this.queue.then(()=>a())}}const appTaskQueue=new TaskQueue;let activeAjaxRequests=0,appGroupingAssignmentState=null,appGroupingAssignmentMenuOpen=!1;$(document).ajaxStart(function(){activeAjaxRequests++});$(document).ajaxStop(function(){activeAjaxRequests--});
function initializeAppGroupingControl(a,b){$("#divAppGroupingAssignment").hide().attr("data-child-app-id",a);appGroupingAssignmentState=null;$.getJSON("/installedapp/grouping/"+b,function(c){const d=(c=c.success?c.grouping:null)&&Array.isArray(c.groups)?c.groups:[],f=$("#divAppGroupingAssignment");0!==d.length&&Number(f.attr("data-child-app-id"))===Number(a)&&(appGroupingAssignmentState={childAppId:Number(a),parentAppId:Number(b),grouping:c},renderAppGroupingAssignmentMenu(),f.show(),appGroupingAssignmentMenuOpen&&
($("#menuAppGroupingAssignment").show(),$("#buttonAppGroupingAssignment").attr("aria-expanded","true")))})}function getSelectedAppGroupId(a,b){return(a=a.groups.find(function(c){return(c.apps||[]).some(function(d){return Number(d.id)===Number(b)})}))?Number(a.id):null}
function buildAppGroupingAssignmentMenuItem(a,b,c){b=$("\x3cbutton\x3e",{type:"button",class:"app-grouping-assignment-option p-menuitem-link p-link",role:"menuitemcheckbox","aria-checked":c,"data-group-id":null===b?"uncategorized":b});c?b.append($("\x3ci\x3e",{class:"fa-regular fa-check p-menuitem-icon","aria-hidden":"true"})):b.append($("\x3cspan\x3e",{class:"p-menuitem-icon app-grouping-assignment-icon-placeholder","aria-hidden":"true"}));b.append($("\x3cspan\x3e",{class:"p-menuitem-text"}).text(a));
return $("\x3cli\x3e",{class:"p-menuitem",role:"none"}).append($("\x3cdiv\x3e",{class:"p-menuitem-content"}).append(b))}
function renderAppGroupingAssignmentMenu(){if(appGroupingAssignmentState){var a=appGroupingAssignmentState.grouping,b=getSelectedAppGroupId(a,appGroupingAssignmentState.childAppId),c=$("#menuAppGroupingAssignment .p-contextmenu-root-list").empty();a.groups.slice().sort(function(d,f){return(d.name||"").localeCompare(f.name||"",void 0,{sensitivity:"base"})}).forEach(function(d){c.append(buildAppGroupingAssignmentMenuItem(d.name,Number(d.id),b===Number(d.id)))});c.append(buildAppGroupingAssignmentMenuItem("Uncategorized",
null,null===b))}}function closeAppGroupingAssignmentMenu(){appGroupingAssignmentMenuOpen=!1;$("#menuAppGroupingAssignment").hide();$("#buttonAppGroupingAssignment").attr("aria-expanded","false")}
function assignAppToGrouping(a){if(appGroupingAssignmentState){var b=appGroupingAssignmentState;if(getSelectedAppGroupId(b.grouping,b.childAppId)===a)closeAppGroupingAssignmentMenu();else{var c=b.grouping.groups.map(function(f){return{id:f.id,name:f.name,apps:(f.apps||[]).filter(function(g){return Number(g.id)!==b.childAppId})}});if(null!==a){const f=c.find(function(g){return Number(g.id)===a});if(!f)return;f.apps.push({id:b.childAppId})}c={groups:c.map(function(f){return{id:f.id,name:f.name,appIds:(f.apps||
[]).map(function(g){return g.id})}})};var d=$("#buttonAppGroupingAssignment, .app-grouping-assignment-option").prop("disabled",!0);$.ajax({url:"/installedapp/grouping/"+b.parentAppId,type:"POST",contentType:"application/json",dataType:"json",data:JSON.stringify(c)}).done(function(f){f.success&&f.grouping?(appGroupingAssignmentState&&appGroupingAssignmentState.childAppId===b.childAppId&&appGroupingAssignmentState.parentAppId===b.parentAppId&&(appGroupingAssignmentState.grouping=f.grouping),renderAppGroupingAssignmentMenu(),
closeAppGroupingAssignmentMenu()):window.alertHubitat(f.message||"Unable to update app group")}).fail(function(){window.alertHubitat("Unable to update app group")}).always(function(){d.prop("disabled",!1)})}}}function toggleAppGroupingAssignmentMenu(a){a.preventDefault();a.stopPropagation();a=$("#menuAppGroupingAssignment");const b=!a.is(":visible");appGroupingAssignmentMenuOpen=b;a.toggle(b);$("#buttonAppGroupingAssignment").attr("aria-expanded",b);return!1}
$(document).on("click",".app-grouping-assignment-option",function(a){a.preventDefault();a.stopPropagation();a=$(this).attr("data-group-id");assignAppToGrouping("uncategorized"===a?null:Number(a))});$(document).on("click",function(a){0===$(a.target).closest("#divAppGroupingAssignment").length&&closeAppGroupingAssignmentMenu()});$(document).on("keydown","#buttonAppGroupingAssignment, .app-grouping-assignment-option",function(a){"Escape"===a.key&&(closeAppGroupingAssignmentMenu(),$("#buttonAppGroupingAssignment").trigger("focus"))});
const appTemplateError='\x3cdiv class\x3d"mdl-grid"\x3e\x3cdiv class\x3d"mdl-card mdl-shadow--2dp mdl-cell mdl-cell--10-col" style\x3d"float: none;margin: 0 auto;"\x3e\x3cdiv class\x3d"panel-body"\x3e\x3ch2 style\x3d"padding:8px;"\x3eUnexpected Error\x3c/h2\x3e\x3ch4 style\x3d"padding:8px;"\x3eAn unexpected error has occurred trying to load the app. Check \x3ca href\x3d"/logs"\x3eLogs\x3c/a\x3e for more information.\x3c/h4\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e';
$(document).ready(function(){debug=(new URL(window.location)).searchParams.get("debug");"true"==debug&&log("Debug is Enabled");updateSelect2()});
$(document).on("click",".hideable",function(){log("click event from a .hideable class element");var a=$(this).data("sectionname"),b=$(this).data("target");$(this).hasClass("collapsed")?(log("element has a collapsed class"),$("#"+b).fadeIn(),$(".selectpicker[multiple]").SumoSelect(),$(this).removeClass("collapsed"),hideableCollapseCallback(appId,a,!1)):(log("element does not have a collapsed class"),$("#"+b).fadeOut(),$(this).addClass("collapsed"),hideableCollapseCallback(appId,a,!0))});
$(document).on("blur","input.submitOnChange[type\x3dtime]",function(a){log("soc from time element");log("blur event from an input type of time with submitOnChange");a.preventDefault();a.stopPropagation();a=$(this).val();/^([0-2]?[0-9]|2[0-3]):[0-5][0-9]$/.test(a)&&(log("calling changeSubmit"),changeSubmit(this))});$(document).on("mousedown",".app-password-toggle",function(a){a.preventDefault()});
$(document).on("click",".app-password-toggle",function(a){a.preventDefault();var b=$(this).siblings("input").get(0);b&&(a="password"===b.type,b.type=a?"text":"password",b=a?"Hide password":"Show password",$(this).attr("aria-label",b).attr("aria-pressed",a).attr("title",b).find("i").toggleClass("fa-eye",!a).toggleClass("fa-eye-slash",a))});$(document).on("focus",".submitOnChange",function(a){log("focus event in a submitOnChange class")});$(document).on("blur",".submitOnChange",function(a){log("blur event from submitOnChange class form-action buttons are enabled")});
var submitOnEveryChangeTimeout,submitOnEveryChangeTarget=null,submitOnEveryChangePosition=0;const submitOnEveryChangeDelay=500;
$(document).on("input","input.submitOnEveryChange[type\x3dtext]",function(a){log("keypress event from a submitOnEveryChange class");clearTimeout(submitOnEveryChangeTimeout);const b=this;submitOnEveryChangeTimeout=setTimeout(function(){submitOnEveryChangeTarget=a.target.id;submitOnEveryChangePosition=a.target.selectionStart;a.preventDefault();log("calling changeSubmit");changeSubmit(b)},submitOnEveryChangeDelay)});
$(document).on("change",".submitOnChange",function(a){log("change event from a submitOnChange class");"time"==$(this).attr("type")||$(this).hasClass("selectpicker")||(log(this.className),log("soc from any .submitOnChange"),a.preventDefault(),log("calling changeSubmit"),changeSubmit(this))});$(document).on("change",".mdl-switch",function(a){log("change event from mdl-switch class");$("[name\x3d'"+a.target.id+"']").val($(this).is(".is-checked"))});
$(document).on("change","textarea.form-control",function(a){log("change event from a textarea formcontrol class");"textarea"==$(this).attr("type")&&(this.innerHTML=this.value)});
$(document).on("change",".checkall input",function(){log("change event from an input with checkall class");for(var a=$(this).parent().parent().siblings(".modal-body").find(".checkbox"),b=0,c=a.length;b<c;b++){var d=a[b];$(this).parent().hasClass("is-checked")?(log("checkbox checked"),d.firstChild.MaterialCheckbox.check()):(log("checkbox unchecked"),d.firstChild.MaterialCheckbox.uncheck())}});
$(document).on("change",".check",function(){log("change event from check class");for(var a=0,b=document.querySelectorAll(".check").length;a<b;a++)document.querySelector("#checkall")&&($(".check input:checked").length==$(".check input").length?(log("checkbox checked"),document.querySelector("#checkall").MaterialCheckbox.check()):(log("checkbox unchecked"),document.querySelector("#checkall").MaterialCheckbox.uncheck()))});
$(document).on("click",".device-save",function(a){$(".device-list").is(":visible")&&(log("click event while device list is visible"),a.preventDefault(),log("a device-list was visible and it was visibile so will click its sibling button"),$(".device-list:visible").siblings("button").click())});
$(document).on("click",function(a){$(".device-list").is(":visible")&&!$(a.target).closest(".device-list").is(":visible")&&(log("click event while device list is visible"),a.preventDefault(),log("a device-list was visible and it was visibile so will click its sibling button"),$(".device-list:visible").siblings("button").click())});
$(document).on("click",".btn-device, .btn-device-required",function(a){log("click event on a btn-device or btn-device-required class");var b=$(this);log(b);var c=b.data("capability"),d=b.data("elemname"),f=b.data("multiple"),g=(b=b.data("ignore"))?b.toString().split(","):[],m="radio";f&&(m="checkbox");var l=$(this).siblings(".device-list").first();if($(l).is(":hidden")){log("dropdown is hidden");var q=$(l).find(".modal-body");q.html("");log(c);log("getting list of devices from endpoint");$.getJSON("/device/listJson?capability\x3d"+
c,function(e){e=e.filter(k=>!g.includes(k.id.toString()));"radio"==m?(log("list type is radio (single select)"),e=e.map(function(k){return'\x3cdiv class\x3d"'+m+'"\x3e\x3clabel class\x3d"device-select-label device-select-item mdl-radio mdl-js-radio" for\x3d"'+d+k.id+'"\x3e\x3cinput class\x3d"mdl-radio__button" type\x3d"'+m+'" name\x3d"'+d+'" value\x3d"'+k.id+'" id\x3d"'+d+k.id+'"\x3e\x3cspan class\x3d"mdl-radio__label"\x3e'+k.displayName+"\x3c/span\x3e\x3c/label\x3e\x3c/div\x3e"})):(log("list type is not radio (multiple select)"),
e=e.map(function(k){return'\x3cdiv class\x3d"'+m+'"\x3e\x3clabel class\x3d"device-select-label device-select-item mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect check" for\x3d"'+d+k.id+'"\x3e\x3cinput class\x3d"mdl-checkbox__input" type\x3d"'+m+'" name\x3d"'+d+'" value\x3d"'+k.id+'" id\x3d"'+d+k.id+'"\x3e\x3cspan class\x3d"mdl-checkbox__label"\x3e'+k.displayName+"\x3c/span\x3e\x3c/label\x3e\x3c/div\x3e"}));e.length&&(log("returned items (devices) has length"),e=e.join(""),q.append(e),q.append('\x3cinput type\x3d"hidden" id\x3d"fieldToUpdate" value\x3d"'+
d+'"/\x3e'),componentHandler.upgradeDom(),e=$(jq("settings["+d+"]")).val(),log(e),0<e.length&&(e=e.split(","),$.each(e,function(k,n){$(".device-select-item").find("input[value\x3d'"+n+"']").parent().addClass("is-checked")})));$(".modal-body").css("height",$("#deviceDialog").height()-180+"px");l.fadeIn();l[0].scrollIntoView({behavior:"instant",block:"end",inline:"nearest"});a.preventDefault()})}else{log("dropdown is visible");l=$(this).siblings(".device-list").first();q=$(l).find(".modal-body");var p=
[],h="";q.find(".device-select-item").each(function(e){$(this).is(".is-checked")&&(log("Found checked item"),p.push($(this).find("input").val()),$(l).find("label[for\x3d'"+$(this).attr("name")+"']").text(),h+=$(this).text()+"\x3cbr/\x3e")});h=h.replace(/,\s*$/,"");c=$(l).find("#fieldToUpdate").attr("value");$(jq("settings["+c+"]")).val(p);$(jq("settings["+c+"]")).trigger("change");0<h.length?($(document.getElementById(c+"devlist")).html(h),$(document.getElementById(c+"devlist")).parent().removeClass("device-btn-empty"),
$(document.getElementById(c+"devlist")).parent().addClass("device-btn-filled")):($(document.getElementById(c+"devlist")).html($(jq("settings["+c+"]")).attr("placeholder")),$(document.getElementById(c+"devlist")).parent().addClass("device-btn-empty"),$(document.getElementById(c+"devlist")).parent().removeClass("device-btn-filled"));log("hiding dropdown");l.hide();a.preventDefault();a.stopPropagation()}});
function updateSelect(a){log("update Select called");var b=a.find(".optiondefault");0!=a.prop("selectedIndex")?(b.prop("disabled",!1),b.css("display","block"),b.removeAttr("selected"),b.html("No selection"),a.prop("selected",!0)):(b.prop("disabled",!0),b.css("display","none"),b.attr("selected","selected"),b.html("Click to set"),a.val(null))}
$(document).on("mousedown","label.device-select-item",function(){log("mousedown on a label with device-select-item class");var a=$(this);if(a.hasClass("is-checked")){var b=function(){setTimeout(function(){a.removeClass("is-checked")},0)},c=function(){a.unbind("mouseup",d)},d=function(){b();c()};a.bind("mouseup",d);a.one("mouseout",c)}});
function disableAppActions(a){a=$(a);if(a.prop("disabled")||"true"===a.attr("aria-disabled"))return!1;$(".form").find("button, input[type\x3dbutton], input[type\x3dsubmit], .app-button-link").add(a).each(function(){const b=$(this);b.addClass("p-disabled");b.is("button, input")?b.prop("disabled",!0):b.attr("aria-disabled","true").css("cursor","not-allowed")});return!0}
$(document).on("click","#fieldsetAppButtons button",function(){const a=this;"Remove"!==a.value&&setTimeout(function(){disableAppActions(a)},0)});function confirmAppAction(a){const b=$(a).data("confirmation-message")||"Are you sure?";window.confirmHubitat(b,function(){confirmed=!0;confirmationPending=!1;buttonClick(a)})}
function buttonClick(a){if(appUseBrowserTaskQueue){if(!a.inTaskQueue){a.inTaskQueue=!0;setTimeout(()=>{appTaskQueue.add(()=>{buttonClick(a)})},100);return}if(0<activeAjaxRequests){setTimeout(()=>{buttonClick(a)},100);return}}log("buttonClick function called");if(confirmationPending)setTimeout(()=>{buttonClick(a)},100);else if(0!=confirmed&&disableAppActions(a)){showHeaderSpinner();confirmed=!0;var b=$(a).siblings("input:hidden").attr("name"),c=$(a).parent().prev().find("[name$\x3d'.type']"),d=$(a).hasClass("submitOnChange"),
f=$(a).data("stateattribute");saveAppScrollPosition();f={id:appId,name:c.attr("name").replace(".type",""),stateAttribute:f};f[b]="clicked";f[c.attr("name")]="button";$.post("/installedapp/btn",f,function(g){"success"==g.status&&(d?changeSubmit(a):window.location.reload())},"json")}}
function changeSubmit(a){if(appUseBrowserTaskQueue){if(!a.inTaskQueue){a.inTaskQueue=!0;setTimeout(()=>{appTaskQueue.add(()=>{changeSubmit(a)})},100);return}if(0<activeAjaxRequests){setTimeout(()=>{changeSubmit(a)},100);return}}log("changeSubmit function called");saveAppScrollPosition();"checkbox"==$(a).attr("type")&&($("[name\x3d'"+a.id+"']").val($(a).parent().is(".is-checked")),a.value=$(a).parent().is(".is-checked"));log("jsonSubmit called");disableAppActions(a);jsonSubmit(a.name,a.value,!1)}
function reloadAppPage(){var a=window.location.pathname.replace("/configure/","/configure/json/");""!=pageName&&pageName!=a.split("/")[a.split("/").length-1]&&(a+="/"+pageName);$.getJSON(a,function(b){try{if(model=b,model.toString().startsWith("\x3c!doctype html\x3e"))updateMainContentWithErrorMessage();else{var c=Handlebars.templates.main(model);updateMainContent(c,!0);$(".form").css({"pointer-events":"unset",opacity:"1"})}}catch(d){$(".panel-body").html("Error Getting Page Data... "+d)}})}
$(document).on("click","input[type\x3dbutton], button[type\x3dbutton]",function(a){if(!a.currentTarget.classList.contains("app-password-toggle")&&!a.currentTarget.classList.contains("p-component"))if($(this).hasClass("hrefElem")&&($(this).prop("disabled",!0),$(this).addClass("text-gray-500")),log("click event from input type of button or button type of button"),"Remove"==a.target.value)log("button value is Remove"),a.preventDefault(),window.confirmHubitat(`Remove ${document.title} now?`,function(){var c=
parseInt(a.target.dataset.childcount||0),d=parseInt(a.target.dataset.childdevicecount||0);if(c||d){console.log("confirmation is required");c=0<c?`${c} child app${1<c?"s":""}`:"";d=0<d?`${d} child device${1<d?"s":""}`:"";const f="This will remove "+c+(c&&d?" and ":"")+d+". Are you sure?";setTimeout(()=>{window.confirmHubitat(f,function(){log("jsonSubmit called");disableAppActions(a.target);jsonSubmit(a.target.name,a.target.value)})},100)}else log("jsonSubmit called"),disableAppActions(a.target),jsonSubmit(a.target.name,
a.target.value)});else if("button"==a.target.value)log("button value is button, calling buttonClick()"),buttonClick(this);else if("modal"==$(a.currentTarget).data("toggle")||$(a.currentTarget).hasClass("device-text")||$(a.currentTarget).hasClass("close"))log("button data is modal or has class device-text or has class close so doing nothing");else{log("button default action, should be a page navigation request");const c=this.name.startsWith("_action_href_name");c&&saveAppScrollPosition();var b={previousPage:model.configPage.previousPage,
currentPage:model.configPage.name};log("name"+model.configPage.name);history.pushState(b,"",window.location.pathname);jsonSubmit(a.currentTarget.name,a.currentTarget.value,!0,!1,c)}});
var jsonSubmit=function(a,b,c,d,f){if(c){var g=$(".required, :input[required]:visible, is-invalid"),m=!0,l=0;$("#formApp")[0].checkValidity()||($("#formApp input:not(:hidden)").each(function(h,e){$(e).next().hasClass("validation")||$(e).after('\x3cdiv class\x3d"validation"\x3e'+e.validationMessage+"\x3c/div\x3e")}),m=!1,l++);$(g).each(function(h,e){e.checkValidity()||(l++,m=!1);$(e).each(function(k,n){n.name&&-1!=n.name.indexOf("settings[")&&((k=document.getElementById(n.name))&&"undefined"!=typeof k.selectedOptions?
0==k.selectedOptions.length&&(m=!1,l++,g.css("border","1px solid #CC2D3B"),g.filter("select").parent().css("border","1px solid #CC2D3B"),$(e).parent(".form-group").css("border","1px solid #CC2D3B")):0==n.value.length&&(m=!1,l++,g.css("border","1px solid #CC2D3B"),g.filter("select").parent().css("border","1px solid #CC2D3B"),$(e).parent(".form-group").css("border","1px solid #CC2D3B")))});0==m&&(log("form complete is false"),g.css("border","1px solid #CC2D3B"),g.filter("select").parent().css("border",
"1px solid #CC2D3B"))});0<$(".device-btn-empty.btn-device-required").length&&(g.css("border-bottom","1px solid #CC2D3B"),g.filter("select").parent().css("border","1px solid #CC2D3B"),m=!1,alert("Please complete the required fields (ones with a *)"))}refreshInterval&&(log("clearing refreshInterval"),clearInterval(refreshInterval));var q=$(".form :input, .form select, .form textarea").not(":input[type\x3dbutton]"),p={};null!=a&&(p[a]=b);q.each(function(h,e){this.type.startsWith("select")&&1==this.multiple?
p[this.name]=JSON.stringify($(this).val()).toString():0==this.type.startsWith("select")&&0==this.type.startsWith("hidden")?p[this.name]=removeTags($(this).val()):p[this.name]=$(this).val()});!c||m?(log("if not validate and is complete (true)"),$(".form").css({"pointer-events":"none",opacity:"1"}),$(".buttons.form-actions").prop("disabled",!0),showHeaderSpinner(),log("posting data to update/json endpoint"),$.post("/installedapp/update/json",p,function(h){if("success"==h.status){log("got data back / success");
if(h.location)log("got a location, redirecting"),window.location=h.location;else if(d)$(".form").css({"pointer-events":"unset",opacity:"1"}),$(".buttons.form-actions").prop("disabled",!1),0==activeAjaxRequests&&hideHeaderSpinner();else{log("got data rendering new view");model=h;if(model.toString().startsWith("\x3c!doctype html\x3e"))updateMainContentWithErrorMessage();else{var e=Handlebars.templates.main(h);updateMainContent(e,!0);$(".form").css({"pointer-events":"unset",opacity:"1"});$(".buttons.form-actions").prop("disabled",
!1);0==activeAjaxRequests&&hideHeaderSpinner()}e=h.app.name;h.app.label&&(e=h.app.label);window.globalAppLabel=e;log("in appUI refresh interval is "+h.configPage.refreshInterval);0<parseInt(h.configPage.refreshInterval)?(log("refreshInterval is "+h.configPage.refreshInterval),clearInterval(refreshInterval),refreshInterval=setInterval(function(){log("calling /update/json from refreshInterval Timer");var k=window.location.pathname.replace("/configure/","/configure/json/");""!=pageName&&pageName!=k.split("/")[k.split("/").length-
1]&&(k+="/"+pageName);$.getJSON(k,function(n){try{if(model=n,model.toString().startsWith("\x3c!doctype html\x3e"))updateMainContentWithErrorMessage();else{var r=Handlebars.templates.main(model);updateMainContent(r,!0);$(".form").css({"pointer-events":"unset",opacity:"1"});log(n.configPage.refreshInterval);0>=parseInt(n.configPage.refreshInterval)&&clearInterval(refreshInterval)}}catch(t){$(".panel-body").html("Error Getting Page Data... "+t)}})},1E3*parseInt(model.configPage.refreshInterval))):clearInterval(refreshInterval);
if(1==c)return log("validate is true"),h={previousPage:model.configPage.previousPage,currentPage:model.configPage.name},e=window.location.pathname.split("/"),-1<e.indexOf(model.configPage.name)&&e[e.length-1]==model.configPage.name||void 0==model.configPage.name?e=e.join("/"):-1<e.indexOf(model.configPage.name)?(e.splice(e.indexOf(model.configPage.name)+1,e.length-e.indexOf(model.configPage.name)),e=e.join("/")):e=e.join("/")+"/"+model.configPage.name,log("name"+model.configPage.name),log("updating window history with replaceState"),
window.history.replaceState(h,"",e),f?resetAppScrollPosition():restoreAppScrollPosition(),setFocusAfterAppRefresh(),!1}f&&resetAppScrollPosition();setFocusAfterAppRefresh()}},"json").fail(function(h){4==h.readyState&&showUpdateJsonError()}).always(()=>{setTimeout(()=>{0==activeAjaxRequests&&hideHeaderSpinner()},100)})):0<l&&alert("Required Fields missing or not passing validation. Please check red underlined fields and complete the required fields (ones with *)")};
function showUpdateJsonError(){appNavigatingAway||updateMainContentWithErrorMessage()}var appNavigatingAway=!1;$(function(){$(window).on("unload",function(){appNavigatingAway=!0;saveAppScrollPosition()})});
window.addEventListener("popstate",function(a){log("Back or Forth Browser action");var b=window.location.pathname.split("/");b.splice(0,4);if(a.state){log("calling jsonSubmit with currentPage href action");var c=$("#pageBreadcrumbs").val();log(c);c=JSON.parse(decodeURIComponent(c));log(c);log(model.configPage.name);-1<c.indexOf(model.configPage.name)?(c.splice(c.indexOf(model.configPage.name),1),log(encodeURIComponent(JSON.stringify(c))),$("#pageBreadcrumbs").val(encodeURIComponent(JSON.stringify(c))),
log($("#pageBreadcrumbs").val())):$("#pageBreadcrumbs").val(encodeURIComponent(JSON.stringify(b)));jsonSubmit("_action_href_name|"+a.state.currentPage+"|1","",!0)}else log("calling jsonSubmit with path last slash href action"),jsonSubmit("_action_href_name|"+b[b.length-1]+"|1","",!0)});
var updateSelect2=function(){log("in updateSelect2 function");$(".buttons.form-actions").prop("disabled",!1);$(".selectpicker:not([multiple])").each(function(b,c){b=$(c).find(".optiondefault");b.prop("disabled",!1);b.css("display","block");b.removeAttr("selected");0!=$(c).prop("selectedIndex")?b.html("No selection"):b.html($(c).attr("placeholder"));b=$(c).find("option").length;$(c).SumoSelect({placeholder:$(c).attr("placeholder"),forceCustomRendering:!1,nativeOnDevice:[],floatWidth:300,search:10<
b});0==$(c).prop("selectedIndex")&&($(c)[0].nextElementSibling.getElementsByTagName("span")[0].innerHTML=$(c).attr("placeholder"));$(c).on("sumo:closed",function(d){$(c).trigger("change");$(this).hasClass("submitOnChange")&&changeSubmit(this)})});$("select[multiple].selectpicker").each(function(){$(this).SumoSelect({placeholder:$(this).attr("placeholder"),triggerChangeCombined:!0,csvDispCount:0,outputAsCSV:!1,isClickAwayOk:!0,forceCustomRendering:!1,nativeOnDevice:[],floatWidth:300});$(this).on("sumo:closed",
function(b){$(this).hasClass("submitOnChange")&&changeSubmit(this)});$(".app-select-toggle-all").click(function(b){b=b.originalEvent;b=b.path||b.composedPath&&b.composedPath();for(var c=0;c<b.length;c++){var d=b[c];if(d.classList.contains("app-select-toggle-all")){d=d.classList.contains("selected");for(c+=1;c<b.length;c++){let f=b[c];if(f.classList.contains("SumoSelect")){b=$(f.children[0])[0];d?b.sumo.selectAll():b.sumo.unSelectAll();break}}break}}})});$.each($(".hideable"),function(b,c){$(c).data("target")});
var a=!1;if(-1<navigator.userAgent.indexOf("Safari")&&-1==navigator.userAgent.indexOf("Chrome")&&0==navigator.maxTouchPoints){const b=navigator.userAgent.match(/Version\/(\d+\.\d+)/);b&&2<=b.length&&(a=14.1>parseFloat(b[1]))}if(a||"24"==clock)$(".safariOnly").show(),$('input[type\x3d"time"]').hide(),$(".timeSetting").each(function(b,c){var d=("#"+c.name).split("[")[1];c=$(c).val();if(null!=c){b="input[name\x3d'hours["+d+"']";var f="input[name\x3d'minutes["+d+"']";d="#amPm-"+d.replace("]","");"24"==
clock?($(d).parent().hide(),$(b).val(c.split(":")[0])):12<=c.split(":")[0]?($(d).val("PM"),12==c.split(":")[0]?$(b).val(parseInt(c.split(":")[0])):$(b).val(parseInt(c.split(":")[0])-12)):($(d).val("AM"),"00"==c.split(":")[0]?$(b).val(parseInt(c.split(":")[0])+12):$(b).val(c.split(":")[0]));$(f).val(c.split(":")[1])}})};
$(document).on("blur, change",".hours, .minutes",function(a){a="input[name\x3d'settings["+this.id.split("[")[1]+"']";var b=$(a).val();void 0!==b&&(b=b.split(":"),b[0]=("0"+$(this).parent().parent().find(".hours").val()).slice(-2),b[1]=$(this).parent().parent().find(".minutes").val(),""==b[0]&&""==b[1]?(log("24 hour time is : empty"),$(a).val("").trigger("change")):(""==b[0]&&(b[0]="12"),""==b[1]&&(b[1]="00"),"hours"==this.id.split("[")[0]&&("24"==clock?b[0]=("0"+$(this).val()).slice(-2):12>=parseInt($(this).val())&&
"PM"==$("#amPm-"+this.id.split("[")[1].replace("]","")).val()?b[0]=parseInt($(this).val())+12:b[0]=("0"+$(this).val()).slice(-2)),"minutes"==this.id.split("[")[0]&&""!=$(this).val()&&(log("minutes"+parseInt($(this).val())+(10>parseInt($(this).val()))),b[1]=("0"+$(this).val()).slice(-2)),log("24 hour time is : "+b.join(":")),$(a).val(b.join(":")).trigger("change")))});
$(document).on("change",".amPm",function(){var a="input[name\x3d'settings["+this.id.split("-")[1]+"]']",b=$(a).val().split(":");log($(this).val());"PM"==$(this).val()&&12>b[0]&&(b[0]=parseInt(b[0])+12);"AM"==$(this).val()&&12<=b[0]&&(b[0]=parseInt(b[0])-12);b[0]=("0"+b[0]).slice(-2);b[1]=("0"+b[1]).slice(-2);$(a).val(b.join(":")).trigger("change");log("am/pm function 24 hour time is : "+b.join(":"))});
function openWindow(a){log("in openWindow function");var b=window.open(a.href,a.title,"resizable,height\x3d"+window.innerHeight+",width\x3d800,left\x3d"+(window.innerWidth/2-400));if(null==b||"undefined"==typeof b)alert("Please allow pop up windows for Hubitat in your browser to continue.");else{b.focus();var c=setInterval(function(){b.closed&&(clearInterval(c),document.getElementsByTagName("html")[0].style.cursor="wait",document.getElementById("formApp").submit())},1E3)}}
$(document).ready(function(){$(window).keydown(function(a){if(13==a.keyCode&&"textarea"!=a.target.type)return $(a.target).blur(),a.preventDefault(),!1});$(document).on("click",".dd",function(a){a.preventDefault();$(this).parent().siblings("input").val($(this).data("value"));$(this).parent().toggle();changeSubmit(this)});$(document).on("click",".dropbtn",function(a){a.preventDefault();$(this).siblings(".dropdown-content").toggle()})});function log(a){"true"==debug&&console.log(a)}
var tagBody="(?:[^\"'\x3e]|\"[^\"]*\"|'[^']*')*",tagOrComment=new RegExp("\x3c(?:!--(?:(?:-*[^-\x3e])*--+|-?)|script\\b"+tagBody+"\x3e[\\s\\S]*?\x3c/script\\s*|style\\b"+tagBody+"\x3e[\\s\\S]*?\x3c/style\\s*|/?[a-z]"+tagBody+")\x3e","gi");function removeTags(a){do{var b=a;a=a.replace(tagOrComment,"")}while(a!==b);return a.replace(/</g,"\x26lt;")}function getAppScrollPositionKey(){return`scrollPosApp-${appId}-${location.pathname}`}
function resetAllAppScrollPositions(){const a=`scrollPosApp-${appId}`;for(let b in localStorage)b.startsWith(a)&&localStorage.removeItem(b)}function saveAppScrollPosition(){const a=$("#divMainUIContent").scrollTop();localStorage.setItem(getAppScrollPositionKey(),a)}function resetAppScrollPosition(){localStorage.setItem(getAppScrollPositionKey(),0);$("#divMainUIContent").scrollTop(0)}
function restoreAppScrollPosition(){const a=localStorage.getItem(getAppScrollPositionKey());a&&$("#divMainUIContent").scrollTop(a)}function updateMainContent(a,b){$("main").html(a);componentHandler.upgradeDom();b&&updateSelect2()}function setFocusAfterAppRefresh(){submitOnEveryChangePosition?setEveryChangeTextInputPosition():appDoNotAutoFocus||isMobile||focusOnFirstEmptyTextInput()}
function setEveryChangeTextInputPosition(){if(submitOnEveryChangePosition&&submitOnEveryChangeTarget){var a=document.getElementById(submitOnEveryChangeTarget);if(a&&submitOnEveryChangePosition){a.focus();try{a.setSelectionRange(submitOnEveryChangePosition,submitOnEveryChangePosition)}catch(b){}a.click();setTimeout(()=>{submitOnEveryChangePosition=0},submitOnEveryChangeDelay-50)}}}function updateMainContentWithErrorMessage(){updateMainContent(appTemplateError)}
function filterCapabilityElements(a){const b=$(a.target.parentElement).next();(a=$(a.target).val())?(b.children("div").hide(),b.children('div:containsCaseInsensitive("'+a+'")').show()):b.children("div").show()}function selectAllCapabilityElements(a){$("#deviceListModal label:visible").addClass("is-checked")}function unselectAllCapabilityElements(a){$("#deviceListModal label:visible").removeClass("is-checked")}
function expandAppUI(){$("#divAppUIContainer").css("width","100%");$("#ulExpandAppUI").hide();$("#ulCollapseAppUI").show();localStorage.setItem(`expandedAppUI-${appId}`,"true");return!1}function collapseAppUI(){$("#divAppUIContainer").css("width","");$("#ulExpandAppUI").show();$("#ulCollapseAppUI").hide();localStorage.removeItem(`expandedAppUI-${appId}`);return!1}function applyAppUIWidth(){localStorage.getItem(`expandedAppUI-${appId}`)?expandAppUI():collapseAppUI()}
function applyAppEmbeddedMode(){const a=document.getElementById("divAppUIContainer");a.style.margin="0";a.style.width="100%";document.getElementById("divAppUISettings").style.display="none"}function hideableCollapseCallback(a,b,c){$.get("/installedapp/collapseCallback/"+a+"/"+encodeURI(b))}
function openDeviceEventSocket(){const a=new WebSocket(("https:"==location.protocol?"wss":"ws")+"://"+location.hostname+":"+(location.port?location.port:"https:"==location.protocol?"443":"80")+"/eventsocket");a.onmessage=function(b){const c=JSON.parse(b.data);b=null;try{switch(c.source){case "DEVICE":b="device-current-state-"+c.deviceId+"-"+c.name.replace(/[^a-zA-Z0-9]/g,"");break;case "APP":b="app-state-"+c.installedAppId+"-"+c.name.replace(/[^a-zA-Z0-9]/g,"");break;case "HUB":b="hub-state-"+c.name.replace(/[^a-zA-Z0-9]/g,
"");break;case "LOCATION":if(c.name.startsWith("variable:")){let d=c.name.replace("variable:",""),f="";for(i=0;i<d.length;i++){const g=d.charCodeAt(i).toString(16);f+=("0"+g).slice(-2)}b="location-state-variable-"+f}else b="location-state-"+c.name.replace(/[^a-zA-Z0-9]/g,"")}}catch(d){console.error("failed to compute target span class",d)}b&&($("."+b).text(c.value),$(".ssr-"+b).each(function(){const d=$(this),f="/installedapp/ssr/"+appId;c.elementId=d.attr("id");fetch(f,{method:"POST",body:JSON.stringify(c)}).then(g=>
g.text()).then(g=>{d.html(g)})}))};a.onclose=function(b){var c="Idle Timeout"==b.reason?1:1E3;console.log("websocket is closed, reconnecting in "+c+"ms",b.reason);setTimeout(function(){openDeviceEventSocket()},c)};a.onerror=function(b){console.error("Socket encountered error: ",b.message,"Closing socket");a.close()}};