'use strict';Handlebars.logger.level=0;Handlebars.registerHelper("is",function(a,b,c){return a&&b&&a.toString()==b.toString()?c.fn(this):c.inverse(this)});Handlebars.registerHelper("isOr",function(a,b,c,d,h){if(a&&b&&c&&d)return a==b||c==d?h.fn(this):h.inverse(this)});Handlebars.registerHelper("isNot",function(a,b,c){return void 0==a||void 0==b?c.fn(this):a&&b&&a.toString()!=b.toString()?c.fn(this):c.inverse(this)});
Handlebars.registerHelper("isSetOrTrue",function(a,b){return void 0==a||1==a?b.fn(this):b.inverse(this)});Handlebars.registerHelper("isGreater",function(a,b,c){return parseInt(a)<parseInt(b)?c.fn(this):c.inverse(this)});Handlebars.registerHelper("isLessThan",function(a,b,c){"*"===a&&(a="-99999999999");"*"===b&&(b="99999999999");return parseInt(a)<parseInt(b)?c.fn(this):c.inverse(this)});Handlebars.registerHelper("ifOr",function(a,b,c){return a||b?c.fn(this):c.inverse(this)});
Handlebars.registerHelper("ifNot",function(a,b){return a?b.inverse(this):b.fn(this)});Handlebars.registerHelper("contains",function(a,b,c){return a&&0<=a.indexOf(parseInt(b))?c.fn(this):c.inverse(this)});Handlebars.registerHelper("startsWith",function(a,b,c){return a.toString().startsWith(b.toString())?c.fn(this):c.inverse(this)});Handlebars.registerHelper("startsWithOr",function(a,b,c,d){return a.toString().startsWith(b.toString())||a.toString().startsWith(c)?d.fn(this):d.inverse(this)});
Handlebars.registerHelper("capitalizeFirst",function(a,b){return a.toString().capitalize()});Handlebars.registerHelper("join",function(a,b){return a.join(", ").toString()});Handlebars.registerHelper("formatDate",function(a,b){return(new DateTool).format("yyy-MM-dd hh:mm:ss z",date)});Handlebars.registerHelper("integerToHexString",function(a,b){return a?(new HexUtils).integerToHexString(a,b):""});Handlebars.registerHelper("replace",function(a,b,c){return a.toString().replace(b,c)});
Handlebars.registerHelper("addOne",function(a){return parseInt(a)+1});Handlebars.registerHelper("stripSpaces",function(a){if(a)return a.toString().replaceAll(" ","")});Handlebars.registerHelper("getClassName",function(a){if(a)return a instanceof Array?"array":a instanceof Object?"object":"string"==typeof a?"string":"unknown"});Handlebars.registerHelper("findSize",function(a){if(a)return a.size()});Handlebars.registerHelper("findLength",function(a){if(a)return a=new JSONObject(a),a.map.length()});
Handlebars.registerHelper("splitLeft",function(a){return a?a.split("..")[0]:a});Handlebars.registerHelper("splitRight",function(a){return a?a.split("..")[1]:a});Handlebars.registerHelper("lookup2",function(a,b){if(a)return a[b]});Handlebars.registerHelper("stripBrackets",function(a){return a.toString().contains(",")?a:a.toString().replace("[","").replace("]","")});Handlebars.registerHelper("toArray",function(a,b){if(a)return a.toString().split(",")});
Handlebars.registerHelper("encode",function(a,b){return encodeURIComponent(JSON.stringify(a))});Handlebars.registerHelper("deviceNames",function(a,b,c){if(a&&(a=a[b])){a=Object.values(a).sort(Intl.Collator().compare);if(!1===c||"false"===c)a.length=Math.min(a.length,1);return a.toString().replaceAll(",","\x3cbr/\x3e")}});
Handlebars.registerHelper("deviceIds",function(a,b,c){if(a&&(a=a[b])){b=[];let h=Object.keys(a).length;if(!1===c||"false"===c)h=Math.min(h,1);for(c=0;c<h;c++){var d=Object.keys(a)[c];b.push(d)}return b}});Handlebars.registerHelper("buildCols",function(a,b){void 0==a&&(a=12);return 1==b?"mdl-cell mdl-cell--"+a+"-col newLine":"mdl-cell mdl-cell--"+a+"-col"});Handlebars.registerHelper("convertToTime",function(a){if(a){var b=new moment(a);return isNaN(b.hours())?a:("0"+b.hour()).slice(-2)+":"+("0"+b.minute()).slice(-2)}return a});
Handlebars.registerHelper("timeToAMPM",function(a){return a?(new moment(a)).format("h:mm A"):a});Handlebars.registerHelper("getKey",function(a){return Object.keys(a)[0].toString()});Handlebars.registerHelper("buttonSOC",function(a){return void 0==a||1==a?"submitOnChange":""});Handlebars.registerHelper("getValue",function(a,b){return a[b]});
Handlebars.registerHelper("processReturnPath",function(a,b){return void 0!=b?"list"===b?"/installedapp/list?section\x3d"+(globalMenuSelection||"").toLowerCase():a:a});
Handlebars.registerHelper("setOptions",function(a,b,c,d){var h="";$.each(b,function(k,e){var f="";if(e&&"object"==typeof e){var l=Object.keys(e)[0],m=e[l];d[a]?d[a]==l?f='selected\x3d"selected"':0!=Object.keys(d[a]).length&&"object"==typeof d[a]&&0<d[a].filter(g=>g==l).length&&(f='selected\x3d"selected"'):void 0!=c&&(c==m||c==l?f='selected\x3d"selected"':"object"==typeof c&&0<c.filter(g=>g==l).length&&(f='selected\x3d"selected"'));h+=`<option value="${l}" ${f}>${m}</option>\r\n`}if("string"==typeof e||
"number"==typeof e)d[a]?d[a]==e?f='selected\x3d"selected"':"object"==typeof d[a]?0<d[a].filter(g=>g==e).length?f='selected\x3d"selected"':"string"==typeof k&&0<d[a].filter(g=>g==k).length&&(f='selected\x3d"selected"'):"string"==typeof k&&d[a]==k&&(f='selected\x3d"selected"'):void 0!=c&&(c==e?f='selected\x3d"selected"':"object"==typeof c&&(0<c.filter(g=>g==e).length||0<c.filter(g=>g==k).length)&&(f='selected\x3d"selected"')),h+=`<option value="${"number"==typeof k?e:k}" ${f}>${e}</option>\r\n`});return h});
Handlebars.registerHelper("setCheckBoxes",function(a,b,c,d){var h="";$.each(b,function(k,e){var f="";if(e&&"object"==typeof e){var l=Object.keys(e)[0],m=e[l];d[a]?d[a]==l?f="checked":0!=Object.keys(d[a]).length&&"object"==typeof d[a]&&0<d[a].filter(g=>g==l).length&&(f="checked"):void 0!=c&&(c==m||c==l?f="checked":"object"==typeof c&&0<c.filter(g=>g==l).length&&(f="checked"));h+=`<input type="checkbox" value="${l}" ${f}>${m}</input><br>\r\n`}if("string"==typeof e||"number"==typeof e)d[a]?d[a]==e?f=
"checked":"object"==typeof d[a]?0<d[a].filter(g=>g==e).length?f="checked":"string"==typeof k&&0<d[a].filter(g=>g==k).length&&(f="checked"):"string"==typeof k&&d[a]==k&&(f="checked"):void 0!=c&&(c==e||c==k?f="checked":"object"==typeof c&&(0<c.filter(g=>g==e).length||0<c.filter(g=>g==k).length)&&(f="checked")),h+=`<input type="checkbox" value="${"number"==typeof k?e:k}" ${f}>${e}</input><br>\r\n`});return h});
Handlebars.registerHelper("setMenuOptions",function(a){var b="";$.each(a,function(c,d){if(d&&"object"==typeof d){var h=Object.keys(d)[0];b+=`<a href="#" class="dd" data-value="${h}">${d[h]}</a>\r\n`}if("string"==typeof d||"number"==typeof d)b+=`<a href="#" class="dd" data-value="${"number"==typeof c?d:c}">${d}</a>\r\n`});return b});Handlebars.registerHelper("toJson",function(a){return JSON.stringify(a)});
Handlebars.registerHelper("concat",function(){let a="";for(let b in arguments)"object"!=typeof arguments[b]&&(a+=arguments[b]);return a});String.prototype.replaceAll=function(a,b){return this.split(a).join(b)};Handlebars.partials=Handlebars.templates;