#!/usr/bin/env python3
"""Generate TOOL_GUIDE.md from the guide the server serves (getToolGuideSections()).

The served sections are the only hand-edited copy: edit them in hubitat-mcp-server.groovy
(or the library method a section delegates to), then run this script. `--check` exits 1
when the committed TOOL_GUIDE.md does not match, which sandbox_lint enforces in CI.
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SERVER = REPO_ROOT / "hubitat-mcp-server.groovy"
LIB_DIR = REPO_ROOT / "libraries"
OUTPUT = REPO_ROOT / "TOOL_GUIDE.md"

HEADER = (
    "# MCP Tool Guide\n\n"
    "<!-- Generated by tools/build-tool-guide.py from getToolGuideSections() in "
    "hubitat-mcp-server.groovy. Do not edit this file; edit the served sections and regenerate. -->\n\n"
    "Detailed reference for MCP Rule Server tools, the same text `hub_get_tool_guide` serves. "
    "Each `##` section below is one `section` key.\n"
)

_ESCAPES = {"b": "\b", "f": "\f", "n": "\n", "r": "\r", "t": "\t", "s": " ",
            "\\": "\\", "'": "'", '"': '"', "$": "$"}
# Consume escape pairs before looking for a closing delimiter (including escaped backslashes).
_TRIPLE_SINGLE_LITERAL = r"'''((?:\\.|(?!''')[^\\])*)'''"


def groovy_unescape(raw: str) -> str:
    """Decode a Groovy ''' string literal body the way the Groovy compiler does."""
    out = []
    i = 0
    while i < len(raw):
        c = raw[i]
        if c != "\\" or i + 1 == len(raw):
            out.append(c)
            i += 1
            continue
        nxt = raw[i + 1]
        if nxt == "\n":  # line continuation
            i += 2
        elif nxt == "u" and re.match(r"[0-9a-fA-F]{4}", raw[i + 2:i + 6]):
            out.append(chr(int(raw[i + 2:i + 6], 16)))
            i += 6
        elif nxt in _ESCAPES:
            out.append(_ESCAPES[nxt])
            i += 2
        else:
            raise ValueError(f"unsupported Groovy escape \\{nxt} near: {raw[max(0, i - 40):i + 10]!r}")
    return "".join(out)


def served_sections(server_src: str, lib_src: str) -> list:
    """Return [(key, text)] in getToolGuideSections() order."""
    block = re.search(r"def getToolGuideSections\(\)\s*\{\s*return\s*\[(.*?)\n\s*\]\s*\}", server_src, re.DOTALL)
    if not block:
        raise ValueError("getToolGuideSections() return literal not found")
    body = block.group(1)
    sections = []
    consumed = 0

    def require_separator(gap):
        remainder = re.sub(r"//[^\n]*|/\*.*?\*/", "", gap, flags=re.DOTALL).strip(" \t\r\n,")
        if remainder:
            raise ValueError(f"unsupported or unparsed guide section near: {remainder[:100]!r}")

    for m in re.finditer(r"^ {8}([a-z_][a-z0-9_]*):\s*(?:" + _TRIPLE_SINGLE_LITERAL + r"|(_\w+)\(\))",
                         body, re.MULTILINE | re.DOTALL):
        require_separator(body[consumed:m.start()])
        consumed = m.end()
        key, literal, method = m.group(1), m.group(2), m.group(3)
        if method:
            mb = re.search(r"(?:String|def)\s+" + re.escape(method)
                           + r"\(\)\s*\{(?:\s|//[^\n]*\n|/\*.*?\*/)*return\s+" + _TRIPLE_SINGLE_LITERAL,
                           lib_src, re.DOTALL)
            if not mb:
                raise ValueError(f"section '{key}' delegates to {method}(), whose ''' literal was not found")
            literal = mb.group(1)
        sections.append((key, groovy_unescape(literal)))
    require_separator(body[consumed:])
    if not sections:
        raise ValueError("no supported guide sections found")
    return sections


def render(server_src: str, lib_src: str) -> str:
    # The best-practice gate relies on its key being published only by hub_get_tool_guide.
    key = re.search(r"def hubBpsGuideKey\(\)\s*\{\s*'([^']+)'\s*\}", server_src)
    if not key:
        raise ValueError("hubBpsGuideKey() literal not found")
    parts = [HEADER]
    for _, text in served_sections(server_src, lib_src):
        parts.append(text.replace(key.group(1), "<served only by hub_get_tool_guide>").strip("\n") + "\n")
    return "\n".join(parts)


def read_sources():
    lib_src = "".join("\n" + p.read_text(encoding="utf-8") for p in sorted(LIB_DIR.glob("*.groovy")))
    return SERVER.read_text(encoding="utf-8"), lib_src


def main(argv) -> int:
    expected = render(*read_sources())
    if "--check" in argv:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print("TOOL_GUIDE.md is out of date: edit getToolGuideSections(), then run python tools/build-tool-guide.py")
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
